### ISSUE TITLE
Survey for session 2017-01

### ISSUE THREAD

**Issue by dertseha** [CodingDojoVie/sessions#21]
January's session set a new record for participants; The registration of 30 places was filled within two days of publication. I'd like to know what makes these people tick in wanting to participate and I am thinking about creating a survey.

Several factors might have contributed; Known so far:
* Dojo with a preset theme ("Legacy Code Refactoring")
* Guest facilitator from Linz (David Tanzer)
* More advertisement than usual (David's peers; FRQ, the venue's company, made an in-house ad)

This issue is about finding the proper set of questions and then document the collected results.

**Comment by dertseha** [comment]
Ideas:
* How well did you like this dojo 1-4 (1: very, 4: not at all)
* What are your reasons to join this dojo ["Topic", "Facilitator", "Venue", "Other" (Specify)]
* Free-text field for any dojo-related comments: Ideas for further dojos; venue proposals; organizational; ...

**Comment by xbojch** [comment]
Perhaps a question to determine if this is their first coding dojo, to be able to see what tips new participants to decide to join.

**Comment by paulroho** [comment]
What about querying the people using adhesive dots and stickies on a flipchart? With this number of participants this could be a more social, interactive and fun experience, easier to prepare and contains the scoring out-of-the-box. So that would trigger an immediate discussion with everyone present.
A quick sketch what I could imagine:
![dojosurvey](https://cloud.githubusercontent.com/assets/721933/22326811/8c52645a-e3b4-11e6-897c-fda0e2b91e4b.jpg)

**Comment by dertseha** [comment]
@paulroho I like this idea, with added bonus of providing a sketch :)
Typically I'm hesitant to bind the people beyond the allotted time, though, putting some dots up should take no time.
This setup looks concise - any other question to add? (perfection is when you can't remove anything anymore...)

I also got the recommendation to perhaps ask people why they want to join during registration in the future.

**Comment by codecop** [comment]
@dertseha yes in the Doodle add second column choose from "topic/facilitator/venue/meet friends"

**Comment by dertseha** [comment]
We had around 28 participants, of which all (20 voters) felt it was a great event.
The majority came for the topic (only 4 for facilitator), and were recurring participants. Only 5 came for the first time, and two for the second (No 3rd dojo visitors). 

Trying to read something out of this, it appears that having known the topic beforehand helps. And that we do have a large base of groupies already, with potential newcomers.

Also thank you to to @codecop for the Doodle approach - I was already thinking about some elaborate Google-Forms ploy, highly over-engineered. :)
