### ISSUE TITLE
Coderetreat Q2/2017

### ISSUE THREAD

**Issue by codecop** [CodingDojoVie/sessions#24]
So we could run another CR in May or June at FRQ? What do you think @dertseha ? Is there still interest to host/sponsor us?

@dertseha said
There's been interest yes, I'll have to check back again.
Though I fear it might be tricky, as the person next in contact for me is under high workload at the moment and possibly foreseeable future.

@dertseha any news on CR location/sponsoring?

@dertseha said
ack, thank you for reminding me - I always forget when at home and remember at work :P
As for hosting a retreat mid-year, yes, willingness is there. The question is mainly: when should it happen? Is there any special slot in May or beginning of June? Is the developers-gang convening in Vienna again?

**Comment by codecop** [comment]
@dertseha no fixed time and no guests this spring. GDCR is in November, so May is half a year before it. May or June is nice, as was last year. Possible dates 20.5., 10.6., 24.6. to avoid public holidays and long weekends.

**Comment by codecop** [comment]
@dertseha ping. Possible dates 20.5., 10.6., 24.6. to avoid public holidays and long weekends.

**Comment by dertseha** [comment]
Tomorrow, Thursday I'm talking with my superior about it. I guess it'll either be 20th of May or 10th of June. I also need to check with my holiday schedule.

**Comment by dertseha** [comment]
Allright. Frequentis is open to host a coderetreat on the 10th of June. We haven't checked the availability of the room, though that is a minor risk.

The last big question is now: Who will facilitate? Ask among the usual suspects?

**Comment by codecop** [comment]
Maybe we/you can discuss the issue at the break during next Coding Dojo? Otherwise we can organize it all together, like everyone runs a sessions (or better always two of us run a session with overlapping facilitators).

**Comment by dertseha** [comment]
Only one response received ("If no one else volunteers"). It's Sebastian and I asked him now if he's still interested. We can work out a secondary person as well then.

**Comment by codecop** [comment]
Sebastian who? I am ok to facilitate one session. Maybe we can share this in the group. Else I could try to invite someone to facilitate from outside. Would we get funding for inviting a facilitator? I can ask if someone would come on his/her own expenses.

**Comment by codecop** [comment]
Hm, 10th of June. So if we want to do that we need to announce it this week. I am not sure I am available 10th of June, too. Sigh

**Comment by dertseha** [comment]
Sebastian Nozzi, from the Scala group. At a later date than 10th of June we wouldn't have Max' physical support. I'm already not so keen on doing the ad/ticketing stuff again (albeit a known task); Not only is there the prospect of being co-facilitator as well, I'd really like to avoid also being the only host's representative/coordinator.

**Comment by dertseha** [comment]
Sebastian confirmed and he might even ask a colleague to co-facilitate. Furthermore he prefers a date early June since he'll be occupied with his move to Germany later that month.
I'll finalize the "Go" today/tomorrow at work.

**Comment by dertseha** [comment]
We're live!
Eventbrite (main event page): https://www.eventbrite.com/e/coderetreat-in-june-2017-vienna-austria-tickets-34549758257
Softwerkskammer: https://www.softwerkskammer.org/activities/CodingDojoVieCoderetreat201706

**Comment by dertseha** [comment]
Pinging @sebnozzi for organization.

**Comment by dertseha** [comment]
I've set the event to be from 9am to 5:30 pm (instead of 5pm as last year). It does take longer.
Still, running only five sessions (instead of the classic 6) seems more relaxed and better fitting. Still - this is all under the main decision of our new facilitator :)

**Comment by dertseha** [comment]
Also, to vent a little about this Eventbrite: Always double and triple check the event page. AGAIN I missed to update the ticket sale dates from the copied event, which of course were from last year - and thus ended.

At least I changed the payment type for the tickets to Eventbrite, which allows SEPA to be picked as an option. Let's see if this option is more accepted now.

**Comment by sebnozzi** [comment]
Hello there ;-)

@codecop A pity you couldn't make it! But if there is a possibility, I would love to co-moderate with you.
 Even if it's one session (why only one? do you have to leave or you want to be on the "participant" side?).

@dertseha You can start asking in a bigger round. Not sure a colleague of mine will be available for this. Ideally it should be somebody familiar with design questions and who has some coding-dojo experience.

**Comment by dertseha** [comment]
First of all, thank you @sebnozzi for taking up the role 👍 

My impression with only 5 rounds is that it is more relaxed. You still try to time all rounds for a 6th round, only to figure out with all the unintentional "extra 5 minutes" various breaks take, it's not going to happen - or trim the final retrospective way too short.

After all, this is not the "Global Day of Coderetreat", it's just _a_ coderetreat, where structure and content is open - it's only about deliberate practice. It could be a full day of refactoring an old codebase for that matter. It doesn't have to be that either, I just want to point out that it doesn't _need_ to be Game of Life, nor exactly six sessions of ~50 minutes each.
GoL is just a "proven" topic; Easy to understand, multidimensional in its possibilities.
The count of sessions may also be dependent on the size of the group. More people, more egos that want to voice their opinions :)

So, yes, you are completely free to set the layout for the day, if you ever wanted that :)

**Comment by dertseha** [comment]
Pinging @mlem @xbojch @ernst-fastl @paulroho @goerg - Does anyone of you want to be a co-facilitator for the upcoming coderetreat on the 10th of June? I know you didn't volunteer for the primary role, perhaps you are interested in filling in for just one or two sessions.

The role could simply be to be there for times when Sebastian is overwhelmed (however that could happen) or he needs to take a bio-break.

(If you are not interested, feel free to ignore this message ;) )

**Comment by ernst-fastl** [comment]
I can co-facilitate.

btw. I was planning to do the June Dojo. Do you think we should do a Dojo in the same month as a retreat?

**Comment by xbojch** [comment]
Thanks for the offer @dertseha. I'd like to co-facilitate. Doesn't need to be this time (@ernst_fastl already volunteered).

Von meinem iPhone gesendet

**Comment by codecop** [comment]
Sorry for late reply, I was away. I will support the CR but I can not guarantee that I will be able to join because it is the last weekend before we get our new kitchen and there are maybe/likely last minute fixes to be done e.g. electricity/plumbing. In case that everything is well, I will attend.

**hosting**
@dertseha thank you for the hosting tasks like Eventbrite. I wanted to offer my help but you made it happen already.

**length of sessions**
A CR is also a place for the facilitators to learn, so we/you can try 5 sessions 45' each and allow a more relaxed atmosphere in the breaks.

**kata**
I recently did two CR with [Pac-Man](http://codingdojo.org/cgi-bin/index.pl?KataPacMan) as exercise. It is a similar large exercise and has many aspects. This would be an option if you want to try something different. I can provide handouts (even printed in colour if we manage to meet up front), resources and ideas for requirement changes.

I like @dertseha idea to go totally different ways. Yes we could refactor all day, a [legacy code retreat](http://www.jbrains.ca/legacy-code-retreat/) or anything else. Any specific ideas @dertseha 

**facilitators**
For me the power of more facilitators is the ability to compare impressions. I usually ask my co-facilitators "what do you see" and I am always surprised by the answers. This makes the CR also interesting for the facilitator (like pair programming) and also less stressful. Also a group of 3 is working quite well. If I am available I am in to co-facilitate one or two sessions with @sebnozzi

**Comment by sebnozzi** [comment]
@codecop Pacman sounds like a good idea. Generally I like the idea very much to use games as an exercise. Yes, that would be great if you could provide me with some material. If anything, to have some take a look at your ideas / approach - though I have ideas on my own as well ;-)

Regarding the "subject" of the CR, I would like to explore design-subjects (I like refactoring aspects also, which I would integrate into that). I will give more information as I work out the details.

**Comment by dertseha** [comment]
I'm generally open to the topic & format.

Though, before to many ideas run wild: To date we have only three (3) tickets reserved. Asking a few semi-regulars in my vicinity I get the usual "Yes, but..." responses. On the other hand we, at the company, have also not started internal advertisement.

**Comment by sebnozzi** [comment]
@dertseha But it publicly announced over the usual channels, right ... ? (whatever these are ... Softwerkskammer Mailing-List, Twitter, etc.) - Maybe it needs to be announced again? - We will also mention it tomorrow at my company.

**Comment by ernst-fastl** [comment]
Hi guys, long time no comments here. Is the retreat going to happen at 10th? In that case I would schedule the June Dojo late in the month.

Also since I offered to co-facilitate I would like to sync up before. On the other hand @sebnozzi if you want to facilitate this time I am very content with just doing the June Dojo.

**Comment by ernst-fastl** [comment]
ah sorry I ment @xbojch if you want to co-facilitate this time I am happy to let you do that instead of me.

**Comment by codecop** [comment]
@dertseha how are we ticket wise? Probably it is time for last advertisement call on all channels we have?

**Comment by sebnozzi** [comment]
My intention is to explore aspects of design / refactoring / testability (how to make something "interactive" testable). I intend to use the "snake" kata for that, as I have been working with that privately. I still don't have an exact layout of the sessions.

**Comment by codecop** [comment]
awesome @sebnozzi I am looking forward to it

**Comment by dertseha** [comment]
As of today, we have 7 registrations. 
I am highly sceptical. Both in terms of whether we'll reach the minimum attendance (12) and in terms of my motivation trying to reach even this minimum number :/

**Comment by codecop** [comment]
why is 12 minimum attendance?
I will do some advertising. What do we need
* send emails to all colleagues/employees (every facilitator)
* Twitter buzz (every facilitator retweets)
* Softwerkskammer Email reminder (Peter)
* register with Coderetreat page (have you done so? / Peter)
* mail to user groups (I can handle JavaVienna, I guess @sebnozzi can send to Scala, what else can we reach?)
* I can put it as Xing event as well.
Other ideas?

**Comment by dertseha** [comment]
12 is some half-arbitrary number to rectify an event on Saturday in the company. 20 is furthermore the minimum number for a professional catering, below that, it is cheaper to order pizza with the budget than to pay a cook.

Please retry on the coderetreat page. I tried to register, it should have worked, though I couldn't find my entry nor work the page itself to search for it. Since that page gave me an impression of being abandoned, I left it that way.

I will re-send emails in the company tomorrow.
Thank you for your enthusiasm :)

**Comment by sebnozzi** [comment]
@codecop I have no power in the Scala group anymore (I'm not even a co-organiser). But I can enter an event in the "professional software developers" group.

**Comment by sebnozzi** [comment]
Announced: https://www.meetup.com/prodev-vienna/events/240428663/

**Comment by xbojch** [comment]
Thanks for pushing this @codecop. I can advertise it in PHP group and also in WeAreDevelopers (conference page with 3800 devs) and FreeCodeCamp Vienna. I might be able to reach Python devs too. :motivated:

**Comment by codecop** [comment]
Tickets
https://www.eventbrite.com/e/coderetreat-in-june-2017-vienna-austria-tickets-34549758257

**Announcements**

Tweet - DONE
https://twitter.com/codecopkofler/status/870186898593112065 -> pls retweet all

Coderetreat site - tried twice, seems broken

User Groups
* Event in Professional Software Development Event
* Event in Java Vienna Meetup
* Mail to Clojure, PHP, Lambdaheads und Python UG Leaders
* Slack message to Python Austria

**Comment by codecop** [comment]
@dertseha technically 6 ppl are the minimum, to have a new pairing partner each session. Also, e.g. last CodingDojo was very interesting with 6 or 7 in total. A CR with <= 10 ppl could be a success, I understand complications of hosting and sponsoring are not "worth" small groups, so I am ok with your limit. I am also ok with ordering pizza or sth to keep overhead to a minimum.

**Comment by codecop** [comment]
@xbojch waiting for your report of success ;-)
@paulroho do you have options to announce the CR also through TechTalk - more C# devs are always a win

**Comment by xbojch** [comment]
Sorry for not posting back the results @codecop.
My yesterdays intention mail was sort of a report.
But here’s a recap.

Posted in Facebook:
- FreeCodeCamp Vienna
- ViennaPHP
- WeAreDevelopers page (visitor post)
- own timeline (tagged Lemmings I/O)

Twitter:
- re-tweeted your post @codecop

Sent an e-mail to one of the organizers of PyDays Vienna to spread the word in the Python community.

Hope it helps!

**Comment by dertseha** [comment]
As by today we have 13 registrations (excluding my own attendance).
Tomorrow before noon Eventbrite will send out the first reminder mail.

**Comment by ernst-fastl** [comment]
@xbojch do you want to co-facilitate or do you want me to do that?

**Comment by xbojch** [comment]
@ernst-fastl you can take this one.

Von meinem iPhone gesendet

**Comment by dertseha** [comment]
We're at 15 registrations and ticket sales has ended. One further person is unsure to come and I've had two late requests as well.  So we should be around 15-18 people.

@sebnozzi Do you need anything else? The projector has both VGA and HDMI connectors.
Please include a "life saving facts" somewhere at the beginning of your presentation:
```
* Live saving facts
** Fire-alarm: Gather on parking lot (avoid windows)
** Coffee down the hall (cups!)
** Toilets down the hall++
**WiFi -> back of badge
```
I'll be there from around 8:15-8:30.

(I just realized: I registered all the attendees at our reception desk, but not the facilitators. d'oh. I hope they still accept my plea tomorrow...)

**Comment by sebnozzi** [comment]
@dertseha Great. Ok, I will include that info in my slides. Do you have existing slides or pictures (for the gathering point) or is it not necessary? I have a MacBook Pro (2015) so I have HDMI and mini-display-port.

Regarding registration at the desk. Normally I would not care much - but I do if it means I can't have WiFi! (might need it for some reason)

**Comment by dertseha** [comment]
No extra images needed - the gathering point is visible from the training room.

I should be able to get your registration in.

**Comment by ernst-fastl** [comment]
@sebnozzi I tried to ping you on linkedin yesterday. Do you want to have a chat about facilitation today? Anything I should prepare? Alternatively I can be there tomorrow at 8 already and we can go through the agenda tomorrow

**Comment by sebnozzi** [comment]
@ernst-fastl @codecop My idea for the retreat will be something like this (still refining the outline). I want to use the "snake" kata, because I think it's an engaging and interesting problem. Because it offers so much, we will be working on one codebase throughout the day (no "delete your code").

However, I want one of the partners to rotate, to bring "refreshment" to the team, to stimulate new ideas and approaches, and to simulate the situation to have somebody new in the team.

The code will grow, and I will be adding more requirements on each round (e.g. first a lone snake that can only move, then a fixed apple that can be eaten, then a randomly positioned apple).

Together with the requirements, or once the 3 phases of requirements are given, more classic constraints can be added. Here I appeal to @ernst-fastl to give me his feedback on what constraint / twist he would like to "impose" ;-) and think is suitable for the problem.

I was thinking of "talk only through code", "evil ping pong" and what I definitely want to do is at least _some_ of the "object calisthenics" constraints (I really like "no naked primitives", limiting the size of methods and classes, and one that I saw elsewhere on the Internet "private methods are a code-smell").

Feedback appreciated.

@dertseha - Will we have a way for people to identify the programming language they have experience with?

**Comment by sebnozzi** [comment]
After a quick phone call with @ernst-fastl we agreed to do like this: rules for the Kata will be presented at the beginning, but implementation will proceed in three phases. Each session will introduce new constraints. The second session will be "make a test-list" The last session will be a refactoring/OO-calisthenics session. Possible sessions in between "evil ping-pong", "talk only through code", "baby-steps" ...

**Comment by dertseha** [comment]
I will bring the fabric-friendly stickers from last year again, on which people can write whatever we (they) like.

**Comment by codecop** [comment]
Thank you all @dertseha @sebnozzi @ernst-fastl - a full success.
