### ISSUE TITLE
Sessions planned 2015

### ISSUE THREAD

**Issue by codecop** [CodingDojoVie/sessions#4]
4 facilitators, 1 session each month => each facilitator 3 times a a year

done
* Jan - Christian @ FRQ
* Jan - Christian @ FRQ
* Feb - Christian @ FRQ
* Feb - Martin Hillbrand @ OLG
* Mar - Martin Lemanski @ Willhaben
* April - Peter Kofler @ Willhaben
* May - Christian @ FRQ
* June - Ernst @ OLG
* July - Martin Lemanski @ Willhaben
* Aug - Christian @ FRQ
* Sept - Peter @ Stockwerk (with ViennaPHP)
* Oct - Ernst @ OLG
* Nov - Code Retreat @ FRQ
* Dec - Martin Hillbrand @ Catalysts

**Comment by dertseha** [comment]
With the September date already set (9th of September), I'll try to plan the August date for the 18th.

Apart from that, I'd skip the November date to avoid competition with the Coderetreat.

Also, with Ernst joining in, we're already 5 people :)

**Comment by codecop** [comment]
Next year planned in #5

**Comment by masterhilli** [comment]
Btw. yep December is okay. Will be done. @ Catalysts (This time with a doodle for the prefect day ;) ) AS CHRISTMAS DOJO

**Comment by mlem** [comment]
damn, I wanted to host a december session...

**Comment by codecop** [comment]
Ha, that leaves only Feb 2016 for you. Just add to #5 ;-)

**Comment by mlem** [comment]
Its a goal for me :(

**Comment by codecop** [comment]
@mlem can we do the Feb dojo in Semesterferien (2.2. or 4.2.)? I have an international guest in Vienna, who might help/run/participate the Dojo then.

**Comment by mlem** [comment]
yeah, I would like to. But lets talk about it in January (14th)

**Comment by codecop** [comment]
@masterhilli slides for Coding Dojo 201512xx seem to be missing. Was there anything worth adding here?

**Comment by masterhilli** [comment]
@codecop thanks for the remainder ;) also GDCR is missing.... will add it too

**Comment by mlem** [comment]
sign me up for december, please

**Comment by codecop** [comment]
@masterhilli slides still missing ;-)
